/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jsanchez' at '5/29/18 2:25 PM' with Gradle 2.10
 *
 * @author jsanchez, @date 5/29/18 2:25 PM
 */
import java.util.ArrayList;
import java.io.BufferedReader;
import java.io.IOException;
import java.util.HashMap;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public ArrayList<String> getLines(BufferedReader input) throws IOException {
        ArrayList<String> res = new ArrayList<String>();

        try (BufferedReader br = input) {
            String line = br.readLine();

            while (line != null) {
                res.add(line);
                line = br.readLine();
            }
            
            return res;
        }

    }

    public void processVsatInfo(ArrayList<String> lines) {
        JsonArray arr = new JsonArray();
        for (String line : lines) {
            String[] split =  line.split("\\s+");

            String date = split[0];
            String siteId = split[1];
            int beamId = Integer.parseInt(split[2]);
            double lng = Double.parseDouble(split[3]);
            double lat = Double.parseDouble(split[4]);           
           
             found = persons.stream()                        // Convert to steam
                .filter(x -> "jack".equals(x.getName()))        // we want "jack" only
                .findAny()                                      // If 'findAny' then return found
                .orElse(null);

        }
    
    }

}
