import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jsanchez' at '5/29/18 2:25 PM' with Gradle 2.10
 *
 * @author jsanchez, @date 5/29/18 2:25 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertFalse("someLibraryMethod should return 'false'", classUnderTest.someLibraryMethod());
    }
}
